/*
 * generated by Xtext 2.10.0
 */
package de.dlr.sc.virsat.fdir.galileo.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DftScopeProvider extends AbstractDftScopeProvider {

}
