/*
 * generated by Xtext 2.10.0
 */
package de.dlr.sc.virsat.fdir.galileo


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DftStandaloneSetup extends DftStandaloneSetupGenerated {

	def static void doSetup() {
		new DftStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
