/*
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.dlr.sc.virsat.fdir.galileo.ide.contentassist.antlr.internal.InternalDftParser;
import de.dlr.sc.virsat.fdir.galileo.services.DftGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DftParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DftGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DftGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGalileoDftAccess().getAlternatives_3(), "rule__GalileoDft__Alternatives_3");
			builder.put(grammarAccess.getGalileoNodeTypeAccess().getAlternatives(), "rule__GalileoNodeType__Alternatives");
			builder.put(grammarAccess.getNamedTypeAccess().getTypeNameAlternatives_0(), "rule__NamedType__TypeNameAlternatives_0");
			builder.put(grammarAccess.getGalileoDftAccess().getGroup(), "rule__GalileoDft__Group__0");
			builder.put(grammarAccess.getGalileoDftAccess().getGroup_3_0(), "rule__GalileoDft__Group_3_0__0");
			builder.put(grammarAccess.getGalileoDftAccess().getGroup_3_1(), "rule__GalileoDft__Group_3_1__0");
			builder.put(grammarAccess.getGalileoGateAccess().getGroup(), "rule__GalileoGate__Group__0");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getGroup(), "rule__GalileoBasicEvent__Group__0");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getGroup_4(), "rule__GalileoBasicEvent__Group_4__0");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getGroup_5(), "rule__GalileoBasicEvent__Group_5__0");
			builder.put(grammarAccess.getObserverTypeAccess().getGroup(), "rule__ObserverType__Group__0");
			builder.put(grammarAccess.getRDEPTypeAccess().getGroup(), "rule__RDEPType__Group__0");
			builder.put(grammarAccess.getDelayTypeAccess().getGroup(), "rule__DelayType__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup_2(), "rule__Float__Group_2__0");
			builder.put(grammarAccess.getFloatAccess().getGroup_3(), "rule__Float__Group_3__0");
			builder.put(grammarAccess.getGalileoDftAccess().getRootAssignment_1(), "rule__GalileoDft__RootAssignment_1");
			builder.put(grammarAccess.getGalileoDftAccess().getGatesAssignment_3_0_0(), "rule__GalileoDft__GatesAssignment_3_0_0");
			builder.put(grammarAccess.getGalileoDftAccess().getBasicEventsAssignment_3_1_0(), "rule__GalileoDft__BasicEventsAssignment_3_1_0");
			builder.put(grammarAccess.getGalileoGateAccess().getNameAssignment_0(), "rule__GalileoGate__NameAssignment_0");
			builder.put(grammarAccess.getGalileoGateAccess().getTypeAssignment_1(), "rule__GalileoGate__TypeAssignment_1");
			builder.put(grammarAccess.getGalileoGateAccess().getChildrenAssignment_2(), "rule__GalileoGate__ChildrenAssignment_2");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getNameAssignment_0(), "rule__GalileoBasicEvent__NameAssignment_0");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getLambdaAssignment_3(), "rule__GalileoBasicEvent__LambdaAssignment_3");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getDormAssignment_4_2(), "rule__GalileoBasicEvent__DormAssignment_4_2");
			builder.put(grammarAccess.getGalileoBasicEventAccess().getRepairAssignment_5_2(), "rule__GalileoBasicEvent__RepairAssignment_5_2");
			builder.put(grammarAccess.getNamedTypeAccess().getTypeNameAssignment(), "rule__NamedType__TypeNameAssignment");
			builder.put(grammarAccess.getObserverTypeAccess().getObservablesAssignment_1(), "rule__ObserverType__ObservablesAssignment_1");
			builder.put(grammarAccess.getObserverTypeAccess().getObservationRateAssignment_4(), "rule__ObserverType__ObservationRateAssignment_4");
			builder.put(grammarAccess.getRDEPTypeAccess().getRateFactorAssignment_2(), "rule__RDEPType__RateFactorAssignment_2");
			builder.put(grammarAccess.getDelayTypeAccess().getTimeAssignment_2(), "rule__DelayType__TimeAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DftGrammarAccess grammarAccess;

	@Override
	protected InternalDftParser createParser() {
		InternalDftParser result = new InternalDftParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DftGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DftGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
