/**
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.dft;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftFactory
 * @model kind="package"
 * @generated
 */
public interface DftPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dft";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.dlr.de/sc/virsat/fdir/galileo/Dft";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dft";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DftPackage eINSTANCE = de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl.init();

  /**
   * The meta object id for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoDftImpl <em>Galileo Dft</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoDftImpl
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoDft()
   * @generated
   */
  int GALILEO_DFT = 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_DFT__ROOT = 0;

  /**
   * The feature id for the '<em><b>Gates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_DFT__GATES = 1;

  /**
   * The feature id for the '<em><b>Basic Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_DFT__BASIC_EVENTS = 2;

  /**
   * The number of structural features of the '<em>Galileo Dft</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_DFT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoFaultTreeNodeImpl <em>Galileo Fault Tree Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoFaultTreeNodeImpl
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoFaultTreeNode()
   * @generated
   */
  int GALILEO_FAULT_TREE_NODE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Children</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__CHILDREN = 2;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__LAMBDA = 3;

  /**
   * The feature id for the '<em><b>Dorm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__DORM = 4;

  /**
   * The feature id for the '<em><b>Repair</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE__REPAIR = 5;

  /**
   * The number of structural features of the '<em>Galileo Fault Tree Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_FAULT_TREE_NODE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoNodeTypeImpl <em>Galileo Node Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoNodeTypeImpl
   * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoNodeType()
   * @generated
   */
  int GALILEO_NODE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE__TYPE_NAME = 0;

  /**
   * The feature id for the '<em><b>Observables</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE__OBSERVABLES = 1;

  /**
   * The feature id for the '<em><b>Observation Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE__OBSERVATION_RATE = 2;

  /**
   * The feature id for the '<em><b>Rate Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE__RATE_FACTOR = 3;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE__TIME = 4;

  /**
   * The number of structural features of the '<em>Galileo Node Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GALILEO_NODE_TYPE_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft <em>Galileo Dft</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Galileo Dft</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft
   * @generated
   */
  EClass getGalileoDft();

  /**
   * Returns the meta object for the reference '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Root</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getRoot()
   * @see #getGalileoDft()
   * @generated
   */
  EReference getGalileoDft_Root();

  /**
   * Returns the meta object for the containment reference list '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getGates <em>Gates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Gates</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getGates()
   * @see #getGalileoDft()
   * @generated
   */
  EReference getGalileoDft_Gates();

  /**
   * Returns the meta object for the containment reference list '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getBasicEvents <em>Basic Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Basic Events</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoDft#getBasicEvents()
   * @see #getGalileoDft()
   * @generated
   */
  EReference getGalileoDft_BasicEvents();

  /**
   * Returns the meta object for class '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode <em>Galileo Fault Tree Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Galileo Fault Tree Node</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode
   * @generated
   */
  EClass getGalileoFaultTreeNode();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getName()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EAttribute getGalileoFaultTreeNode_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getType()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EReference getGalileoFaultTreeNode_Type();

  /**
   * Returns the meta object for the reference list '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Children</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getChildren()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EReference getGalileoFaultTreeNode_Children();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lambda</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getLambda()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EAttribute getGalileoFaultTreeNode_Lambda();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getDorm <em>Dorm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dorm</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getDorm()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EAttribute getGalileoFaultTreeNode_Dorm();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getRepair <em>Repair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Repair</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getRepair()
   * @see #getGalileoFaultTreeNode()
   * @generated
   */
  EAttribute getGalileoFaultTreeNode_Repair();

  /**
   * Returns the meta object for class '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType <em>Galileo Node Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Galileo Node Type</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType
   * @generated
   */
  EClass getGalileoNodeType();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getTypeName()
   * @see #getGalileoNodeType()
   * @generated
   */
  EAttribute getGalileoNodeType_TypeName();

  /**
   * Returns the meta object for the reference list '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getObservables <em>Observables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Observables</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getObservables()
   * @see #getGalileoNodeType()
   * @generated
   */
  EReference getGalileoNodeType_Observables();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getObservationRate <em>Observation Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Observation Rate</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getObservationRate()
   * @see #getGalileoNodeType()
   * @generated
   */
  EAttribute getGalileoNodeType_ObservationRate();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getRateFactor <em>Rate Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rate Factor</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getRateFactor()
   * @see #getGalileoNodeType()
   * @generated
   */
  EAttribute getGalileoNodeType_RateFactor();

  /**
   * Returns the meta object for the attribute '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.GalileoNodeType#getTime()
   * @see #getGalileoNodeType()
   * @generated
   */
  EAttribute getGalileoNodeType_Time();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DftFactory getDftFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoDftImpl <em>Galileo Dft</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoDftImpl
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoDft()
     * @generated
     */
    EClass GALILEO_DFT = eINSTANCE.getGalileoDft();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_DFT__ROOT = eINSTANCE.getGalileoDft_Root();

    /**
     * The meta object literal for the '<em><b>Gates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_DFT__GATES = eINSTANCE.getGalileoDft_Gates();

    /**
     * The meta object literal for the '<em><b>Basic Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_DFT__BASIC_EVENTS = eINSTANCE.getGalileoDft_BasicEvents();

    /**
     * The meta object literal for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoFaultTreeNodeImpl <em>Galileo Fault Tree Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoFaultTreeNodeImpl
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoFaultTreeNode()
     * @generated
     */
    EClass GALILEO_FAULT_TREE_NODE = eINSTANCE.getGalileoFaultTreeNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_FAULT_TREE_NODE__NAME = eINSTANCE.getGalileoFaultTreeNode_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_FAULT_TREE_NODE__TYPE = eINSTANCE.getGalileoFaultTreeNode_Type();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_FAULT_TREE_NODE__CHILDREN = eINSTANCE.getGalileoFaultTreeNode_Children();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_FAULT_TREE_NODE__LAMBDA = eINSTANCE.getGalileoFaultTreeNode_Lambda();

    /**
     * The meta object literal for the '<em><b>Dorm</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_FAULT_TREE_NODE__DORM = eINSTANCE.getGalileoFaultTreeNode_Dorm();

    /**
     * The meta object literal for the '<em><b>Repair</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_FAULT_TREE_NODE__REPAIR = eINSTANCE.getGalileoFaultTreeNode_Repair();

    /**
     * The meta object literal for the '{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoNodeTypeImpl <em>Galileo Node Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.GalileoNodeTypeImpl
     * @see de.dlr.sc.virsat.fdir.galileo.dft.impl.DftPackageImpl#getGalileoNodeType()
     * @generated
     */
    EClass GALILEO_NODE_TYPE = eINSTANCE.getGalileoNodeType();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_NODE_TYPE__TYPE_NAME = eINSTANCE.getGalileoNodeType_TypeName();

    /**
     * The meta object literal for the '<em><b>Observables</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GALILEO_NODE_TYPE__OBSERVABLES = eINSTANCE.getGalileoNodeType_Observables();

    /**
     * The meta object literal for the '<em><b>Observation Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_NODE_TYPE__OBSERVATION_RATE = eINSTANCE.getGalileoNodeType_ObservationRate();

    /**
     * The meta object literal for the '<em><b>Rate Factor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_NODE_TYPE__RATE_FACTOR = eINSTANCE.getGalileoNodeType_RateFactor();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GALILEO_NODE_TYPE__TIME = eINSTANCE.getGalileoNodeType_Time();

  }

} //DftPackage
