/**
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.dft;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Galileo Repair Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction#getRepair <em>Repair</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction#getName <em>Name</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction#getObservartions <em>Observartions</em>}</li>
 * </ul>
 *
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoRepairAction()
 * @model
 * @generated
 */
public interface GalileoRepairAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Repair</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repair</em>' attribute.
   * @see #setRepair(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoRepairAction_Repair()
   * @model
   * @generated
   */
  String getRepair();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction#getRepair <em>Repair</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repair</em>' attribute.
   * @see #getRepair()
   * @generated
   */
  void setRepair(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoRepairAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Observartions</b></em>' reference list.
   * The list contents are of type {@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observartions</em>' reference list.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoRepairAction_Observartions()
   * @model
   * @generated
   */
  EList<GalileoFaultTreeNode> getObservartions();

} // GalileoRepairAction
