/**
 * generated by Xtext 2.22.0
 */
package de.dlr.sc.virsat.fdir.galileo.dft;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Galileo Fault Tree Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getName <em>Name</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getType <em>Type</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getChildren <em>Children</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getLambda <em>Lambda</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getProb <em>Prob</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getDorm <em>Dorm</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getRepairActions <em>Repair Actions</em>}</li>
 * </ul>
 *
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode()
 * @model
 * @generated
 */
public interface GalileoFaultTreeNode extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(GalileoNodeType)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Type()
   * @model containment="true"
   * @generated
   */
  GalileoNodeType getType();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(GalileoNodeType value);

  /**
   * Returns the value of the '<em><b>Children</b></em>' reference list.
   * The list contents are of type {@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' reference list.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Children()
   * @model
   * @generated
   */
  EList<GalileoFaultTreeNode> getChildren();

  /**
   * Returns the value of the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' attribute.
   * @see #setLambda(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Lambda()
   * @model
   * @generated
   */
  String getLambda();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getLambda <em>Lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' attribute.
   * @see #getLambda()
   * @generated
   */
  void setLambda(String value);

  /**
   * Returns the value of the '<em><b>Prob</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prob</em>' attribute.
   * @see #setProb(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Prob()
   * @model
   * @generated
   */
  String getProb();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getProb <em>Prob</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prob</em>' attribute.
   * @see #getProb()
   * @generated
   */
  void setProb(String value);

  /**
   * Returns the value of the '<em><b>Dorm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dorm</em>' attribute.
   * @see #setDorm(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_Dorm()
   * @model
   * @generated
   */
  String getDorm();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode#getDorm <em>Dorm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dorm</em>' attribute.
   * @see #getDorm()
   * @generated
   */
  void setDorm(String value);

  /**
   * Returns the value of the '<em><b>Repair Actions</b></em>' containment reference list.
   * The list contents are of type {@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoRepairAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repair Actions</em>' containment reference list.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoFaultTreeNode_RepairActions()
   * @model containment="true"
   * @generated
   */
  EList<GalileoRepairAction> getRepairActions();

} // GalileoFaultTreeNode
