/**
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.dft;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Galileo Node Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getGalileoNodeType()
 * @model
 * @generated
 */
public interface GalileoNodeType extends EObject
{
} // GalileoNodeType
