/**
 * generated by Xtext 2.22.0
 */
package de.dlr.sc.virsat.fdir.galileo.dft;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Observer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.Observer#getObservables <em>Observables</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.Observer#getObservationRate <em>Observation Rate</em>}</li>
 * </ul>
 *
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getObserver()
 * @model
 * @generated
 */
public interface Observer extends GalileoNodeType
{
  /**
   * Returns the value of the '<em><b>Observables</b></em>' reference list.
   * The list contents are of type {@link de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observables</em>' reference list.
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getObserver_Observables()
   * @model
   * @generated
   */
  EList<GalileoFaultTreeNode> getObservables();

  /**
   * Returns the value of the '<em><b>Observation Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observation Rate</em>' attribute.
   * @see #setObservationRate(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getObserver_ObservationRate()
   * @model
   * @generated
   */
  String getObservationRate();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.Observer#getObservationRate <em>Observation Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Observation Rate</em>' attribute.
   * @see #getObservationRate()
   * @generated
   */
  void setObservationRate(String value);

} // Observer
