/**
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.dft;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rdep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.Rdep#getRateFactor <em>Rate Factor</em>}</li>
 * </ul>
 *
 * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getRdep()
 * @model
 * @generated
 */
public interface Rdep extends GalileoNodeType
{
  /**
   * Returns the value of the '<em><b>Rate Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rate Factor</em>' attribute.
   * @see #setRateFactor(String)
   * @see de.dlr.sc.virsat.fdir.galileo.dft.DftPackage#getRdep_RateFactor()
   * @model
   * @generated
   */
  String getRateFactor();

  /**
   * Sets the value of the '{@link de.dlr.sc.virsat.fdir.galileo.dft.Rdep#getRateFactor <em>Rate Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rate Factor</em>' attribute.
   * @see #getRateFactor()
   * @generated
   */
  void setRateFactor(String value);

} // Rdep
