/*
 * generated by Xtext 2.22.0
 */
package de.dlr.sc.virsat.fdir.galileo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDftScopeProvider extends DelegatingScopeProvider {
}
