/*
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DftGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GalileoDftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.GalileoDft");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cToplevelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRootAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRootGalileoFaultTreeNodeCrossReference_1_0 = (CrossReference)cRootAssignment_1.eContents().get(0);
		private final RuleCall cRootGalileoFaultTreeNodeSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cRootGalileoFaultTreeNodeCrossReference_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Assignment cGatesAssignment_3_0_0 = (Assignment)cGroup_3_0.eContents().get(0);
		private final RuleCall cGatesGalileoGateParserRuleCall_3_0_0_0 = (RuleCall)cGatesAssignment_3_0_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Assignment cBasicEventsAssignment_3_1_0 = (Assignment)cGroup_3_1.eContents().get(0);
		private final RuleCall cBasicEventsGalileoBasicEventParserRuleCall_3_1_0_0 = (RuleCall)cBasicEventsAssignment_3_1_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		
		//GalileoDft:
		//	'toplevel' root=[GalileoFaultTreeNode|STRING] ';' (gates+=GalileoGate ';' | basicEvents+=GalileoBasicEvent ';')*;
		@Override public ParserRule getRule() { return rule; }
		
		//'toplevel' root=[GalileoFaultTreeNode|STRING] ';' (gates+=GalileoGate ';' | basicEvents+=GalileoBasicEvent ';')*
		public Group getGroup() { return cGroup; }
		
		//'toplevel'
		public Keyword getToplevelKeyword_0() { return cToplevelKeyword_0; }
		
		//root=[GalileoFaultTreeNode|STRING]
		public Assignment getRootAssignment_1() { return cRootAssignment_1; }
		
		//[GalileoFaultTreeNode|STRING]
		public CrossReference getRootGalileoFaultTreeNodeCrossReference_1_0() { return cRootGalileoFaultTreeNodeCrossReference_1_0; }
		
		//STRING
		public RuleCall getRootGalileoFaultTreeNodeSTRINGTerminalRuleCall_1_0_1() { return cRootGalileoFaultTreeNodeSTRINGTerminalRuleCall_1_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
		
		//(gates+=GalileoGate ';' | basicEvents+=GalileoBasicEvent ';')*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//gates+=GalileoGate ';'
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//gates+=GalileoGate
		public Assignment getGatesAssignment_3_0_0() { return cGatesAssignment_3_0_0; }
		
		//GalileoGate
		public RuleCall getGatesGalileoGateParserRuleCall_3_0_0_0() { return cGatesGalileoGateParserRuleCall_3_0_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_0_1() { return cSemicolonKeyword_3_0_1; }
		
		//basicEvents+=GalileoBasicEvent ';'
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//basicEvents+=GalileoBasicEvent
		public Assignment getBasicEventsAssignment_3_1_0() { return cBasicEventsAssignment_3_1_0; }
		
		//GalileoBasicEvent
		public RuleCall getBasicEventsGalileoBasicEventParserRuleCall_3_1_0_0() { return cBasicEventsGalileoBasicEventParserRuleCall_3_1_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_1_1() { return cSemicolonKeyword_3_1_1; }
	}
	public class GalileoGateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.GalileoGate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeGalileoNodeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cChildrenAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cChildrenGalileoFaultTreeNodeCrossReference_2_0 = (CrossReference)cChildrenAssignment_2.eContents().get(0);
		private final RuleCall cChildrenGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1 = (RuleCall)cChildrenGalileoFaultTreeNodeCrossReference_2_0.eContents().get(1);
		
		//GalileoGate GalileoFaultTreeNode:
		//	name=STRING type=GalileoNodeType children+=[GalileoFaultTreeNode|STRING]*;
		@Override public ParserRule getRule() { return rule; }
		
		//name=STRING type=GalileoNodeType children+=[GalileoFaultTreeNode|STRING]*
		public Group getGroup() { return cGroup; }
		
		//name=STRING
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0() { return cNameSTRINGTerminalRuleCall_0_0; }
		
		//type=GalileoNodeType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//GalileoNodeType
		public RuleCall getTypeGalileoNodeTypeParserRuleCall_1_0() { return cTypeGalileoNodeTypeParserRuleCall_1_0; }
		
		//children+=[GalileoFaultTreeNode|STRING]*
		public Assignment getChildrenAssignment_2() { return cChildrenAssignment_2; }
		
		//[GalileoFaultTreeNode|STRING]
		public CrossReference getChildrenGalileoFaultTreeNodeCrossReference_2_0() { return cChildrenGalileoFaultTreeNodeCrossReference_2_0; }
		
		//STRING
		public RuleCall getChildrenGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1() { return cChildrenGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1; }
	}
	public class GalileoBasicEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.GalileoBasicEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLambdaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLambdaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLambdaFloatParserRuleCall_3_0 = (RuleCall)cLambdaAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDormKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDormAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDormFloatParserRuleCall_4_2_0 = (RuleCall)cDormAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRepairKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRepairAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRepairFloatParserRuleCall_5_2_0 = (RuleCall)cRepairAssignment_5_2.eContents().get(0);
		
		//GalileoBasicEvent GalileoFaultTreeNode:
		//	name=STRING 'lambda' '=' lambda=Float ('dorm' '=' dorm=Float)? ('repair' '=' repair=Float)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=STRING 'lambda' '=' lambda=Float ('dorm' '=' dorm=Float)? ('repair' '=' repair=Float)?
		public Group getGroup() { return cGroup; }
		
		//name=STRING
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0() { return cNameSTRINGTerminalRuleCall_0_0; }
		
		//'lambda'
		public Keyword getLambdaKeyword_1() { return cLambdaKeyword_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//lambda=Float
		public Assignment getLambdaAssignment_3() { return cLambdaAssignment_3; }
		
		//Float
		public RuleCall getLambdaFloatParserRuleCall_3_0() { return cLambdaFloatParserRuleCall_3_0; }
		
		//('dorm' '=' dorm=Float)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'dorm'
		public Keyword getDormKeyword_4_0() { return cDormKeyword_4_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }
		
		//dorm=Float
		public Assignment getDormAssignment_4_2() { return cDormAssignment_4_2; }
		
		//Float
		public RuleCall getDormFloatParserRuleCall_4_2_0() { return cDormFloatParserRuleCall_4_2_0; }
		
		//('repair' '=' repair=Float)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'repair'
		public Keyword getRepairKeyword_5_0() { return cRepairKeyword_5_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }
		
		//repair=Float
		public Assignment getRepairAssignment_5_2() { return cRepairAssignment_5_2; }
		
		//Float
		public RuleCall getRepairFloatParserRuleCall_5_2_0() { return cRepairFloatParserRuleCall_5_2_0; }
	}
	public class GalileoNodeTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.GalileoNodeType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNamedParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObserverParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRDEPParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDelayParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//GalileoNodeType:
		//	Named | Observer | RDEP | Delay;
		@Override public ParserRule getRule() { return rule; }
		
		//Named | Observer | RDEP | Delay
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Named
		public RuleCall getNamedParserRuleCall_0() { return cNamedParserRuleCall_0; }
		
		//Observer
		public RuleCall getObserverParserRuleCall_1() { return cObserverParserRuleCall_1; }
		
		//RDEP
		public RuleCall getRDEPParserRuleCall_2() { return cRDEPParserRuleCall_2; }
		
		//Delay
		public RuleCall getDelayParserRuleCall_3() { return cDelayParserRuleCall_3; }
	}
	public class NamedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.Named");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNamedAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeNameAlternatives_1_0 = (Alternatives)cTypeNameAssignment_1.eContents().get(0);
		private final Keyword cTypeNameAndKeyword_1_0_0 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(0);
		private final Keyword cTypeNameOrKeyword_1_0_1 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(1);
		private final RuleCall cTypeNameXOFYTerminalRuleCall_1_0_2 = (RuleCall)cTypeNameAlternatives_1_0.eContents().get(2);
		private final Keyword cTypeNamePandKeyword_1_0_3 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(3);
		private final Keyword cTypeNamePand_iKeyword_1_0_4 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(4);
		private final Keyword cTypeNamePorKeyword_1_0_5 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(5);
		private final Keyword cTypeNamePor_iKeyword_1_0_6 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(6);
		private final Keyword cTypeNameSandKeyword_1_0_7 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(7);
		private final Keyword cTypeNameHspKeyword_1_0_8 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(8);
		private final Keyword cTypeNameWspKeyword_1_0_9 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(9);
		private final Keyword cTypeNameCspKeyword_1_0_10 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(10);
		private final Keyword cTypeNameSeqKeyword_1_0_11 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(11);
		private final Keyword cTypeNameFdepKeyword_1_0_12 = (Keyword)cTypeNameAlternatives_1_0.eContents().get(12);
		
		//Named GalileoNodeType:
		//	{Named} typeName=('and' | 'or' | XOFY | 'pand' | 'pand_i' | 'por' | 'por_i' | 'sand' | 'hsp' | 'wsp' | 'csp' | 'seq'
		//	| 'fdep');
		@Override public ParserRule getRule() { return rule; }
		
		//{Named} typeName=('and' | 'or' | XOFY | 'pand' | 'pand_i' | 'por' | 'por_i' | 'sand' | 'hsp' | 'wsp' | 'csp' | 'seq' |
		//'fdep')
		public Group getGroup() { return cGroup; }
		
		//{Named}
		public Action getNamedAction_0() { return cNamedAction_0; }
		
		//typeName=('and' | 'or' | XOFY | 'pand' | 'pand_i' | 'por' | 'por_i' | 'sand' | 'hsp' | 'wsp' | 'csp' | 'seq' | 'fdep')
		public Assignment getTypeNameAssignment_1() { return cTypeNameAssignment_1; }
		
		//('and' | 'or' | XOFY | 'pand' | 'pand_i' | 'por' | 'por_i' | 'sand' | 'hsp' | 'wsp' | 'csp' | 'seq' | 'fdep')
		public Alternatives getTypeNameAlternatives_1_0() { return cTypeNameAlternatives_1_0; }
		
		//'and'
		public Keyword getTypeNameAndKeyword_1_0_0() { return cTypeNameAndKeyword_1_0_0; }
		
		//'or'
		public Keyword getTypeNameOrKeyword_1_0_1() { return cTypeNameOrKeyword_1_0_1; }
		
		//XOFY
		public RuleCall getTypeNameXOFYTerminalRuleCall_1_0_2() { return cTypeNameXOFYTerminalRuleCall_1_0_2; }
		
		//'pand'
		public Keyword getTypeNamePandKeyword_1_0_3() { return cTypeNamePandKeyword_1_0_3; }
		
		//'pand_i'
		public Keyword getTypeNamePand_iKeyword_1_0_4() { return cTypeNamePand_iKeyword_1_0_4; }
		
		//'por'
		public Keyword getTypeNamePorKeyword_1_0_5() { return cTypeNamePorKeyword_1_0_5; }
		
		//'por_i'
		public Keyword getTypeNamePor_iKeyword_1_0_6() { return cTypeNamePor_iKeyword_1_0_6; }
		
		//'sand'
		public Keyword getTypeNameSandKeyword_1_0_7() { return cTypeNameSandKeyword_1_0_7; }
		
		//'hsp'
		public Keyword getTypeNameHspKeyword_1_0_8() { return cTypeNameHspKeyword_1_0_8; }
		
		//'wsp'
		public Keyword getTypeNameWspKeyword_1_0_9() { return cTypeNameWspKeyword_1_0_9; }
		
		//'csp'
		public Keyword getTypeNameCspKeyword_1_0_10() { return cTypeNameCspKeyword_1_0_10; }
		
		//'seq'
		public Keyword getTypeNameSeqKeyword_1_0_11() { return cTypeNameSeqKeyword_1_0_11; }
		
		//'fdep'
		public Keyword getTypeNameFdepKeyword_1_0_12() { return cTypeNameFdepKeyword_1_0_12; }
	}
	public class ObserverElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.Observer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cObserverAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cObserverKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cObservablesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cObservablesGalileoFaultTreeNodeCrossReference_2_0 = (CrossReference)cObservablesAssignment_2.eContents().get(0);
		private final RuleCall cObservablesGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1 = (RuleCall)cObservablesGalileoFaultTreeNodeCrossReference_2_0.eContents().get(1);
		private final Keyword cObsRateKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cObservationRateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cObservationRateFloatParserRuleCall_5_0 = (RuleCall)cObservationRateAssignment_5.eContents().get(0);
		
		//Observer GalileoNodeType:
		//	{Observer} 'observer' observables+=[GalileoFaultTreeNode|STRING]* 'obsRate' '=' observationRate=Float;
		@Override public ParserRule getRule() { return rule; }
		
		//{Observer} 'observer' observables+=[GalileoFaultTreeNode|STRING]* 'obsRate' '=' observationRate=Float
		public Group getGroup() { return cGroup; }
		
		//{Observer}
		public Action getObserverAction_0() { return cObserverAction_0; }
		
		//'observer'
		public Keyword getObserverKeyword_1() { return cObserverKeyword_1; }
		
		//observables+=[GalileoFaultTreeNode|STRING]*
		public Assignment getObservablesAssignment_2() { return cObservablesAssignment_2; }
		
		//[GalileoFaultTreeNode|STRING]
		public CrossReference getObservablesGalileoFaultTreeNodeCrossReference_2_0() { return cObservablesGalileoFaultTreeNodeCrossReference_2_0; }
		
		//STRING
		public RuleCall getObservablesGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1() { return cObservablesGalileoFaultTreeNodeSTRINGTerminalRuleCall_2_0_1; }
		
		//'obsRate'
		public Keyword getObsRateKeyword_3() { return cObsRateKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//observationRate=Float
		public Assignment getObservationRateAssignment_5() { return cObservationRateAssignment_5; }
		
		//Float
		public RuleCall getObservationRateFloatParserRuleCall_5_0() { return cObservationRateFloatParserRuleCall_5_0; }
	}
	public class RDEPElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.RDEP");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRdepAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRdepKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRateFactorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRateFactorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRateFactorFloatParserRuleCall_3_0 = (RuleCall)cRateFactorAssignment_3.eContents().get(0);
		
		//RDEP GalileoNodeType:
		//	{Rdep} 'rdep' 'rateFactor' rateFactor=Float;
		@Override public ParserRule getRule() { return rule; }
		
		//{Rdep} 'rdep' 'rateFactor' rateFactor=Float
		public Group getGroup() { return cGroup; }
		
		//{Rdep}
		public Action getRdepAction_0() { return cRdepAction_0; }
		
		//'rdep'
		public Keyword getRdepKeyword_1() { return cRdepKeyword_1; }
		
		//'rateFactor'
		public Keyword getRateFactorKeyword_2() { return cRateFactorKeyword_2; }
		
		//rateFactor=Float
		public Assignment getRateFactorAssignment_3() { return cRateFactorAssignment_3; }
		
		//Float
		public RuleCall getRateFactorFloatParserRuleCall_3_0() { return cRateFactorFloatParserRuleCall_3_0; }
	}
	public class DelayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.Delay");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDelayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDelayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTimeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTimeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTimeFloatParserRuleCall_3_0 = (RuleCall)cTimeAssignment_3.eContents().get(0);
		
		//Delay GalileoNodeType:
		//	{Delay} 'delay' 'time' time=Float;
		@Override public ParserRule getRule() { return rule; }
		
		//{Delay} 'delay' 'time' time=Float
		public Group getGroup() { return cGroup; }
		
		//{Delay}
		public Action getDelayAction_0() { return cDelayAction_0; }
		
		//'delay'
		public Keyword getDelayKeyword_1() { return cDelayKeyword_1; }
		
		//'time'
		public Keyword getTimeKeyword_2() { return cTimeKeyword_2; }
		
		//time=Float
		public Assignment getTimeAssignment_3() { return cTimeAssignment_3; }
		
		//Float
		public RuleCall getTimeFloatParserRuleCall_3_0() { return cTimeFloatParserRuleCall_3_0; }
	}
	public class FloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.Float");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_3_2 = (RuleCall)cGroup_3.eContents().get(2);
		
		//Float:
		//	'-'? INT ('.' INT)? ('e' '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT ('.' INT)? ('e' '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//('.' INT)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'.'
		public Keyword getFullStopKeyword_2_0() { return cFullStopKeyword_2_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2_1() { return cINTTerminalRuleCall_2_1; }
		
		//('e' '-'? INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'e'
		public Keyword getEKeyword_3_0() { return cEKeyword_3_0; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_3_1() { return cHyphenMinusKeyword_3_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3_2() { return cINTTerminalRuleCall_3_2; }
	}
	
	
	private final GalileoDftElements pGalileoDft;
	private final GalileoGateElements pGalileoGate;
	private final GalileoBasicEventElements pGalileoBasicEvent;
	private final GalileoNodeTypeElements pGalileoNodeType;
	private final NamedElements pNamed;
	private final ObserverElements pObserver;
	private final RDEPElements pRDEP;
	private final DelayElements pDelay;
	private final FloatElements pFloat;
	private final TerminalRule tXOFY;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DftGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGalileoDft = new GalileoDftElements();
		this.pGalileoGate = new GalileoGateElements();
		this.pGalileoBasicEvent = new GalileoBasicEventElements();
		this.pGalileoNodeType = new GalileoNodeTypeElements();
		this.pNamed = new NamedElements();
		this.pObserver = new ObserverElements();
		this.pRDEP = new RDEPElements();
		this.pDelay = new DelayElements();
		this.pFloat = new FloatElements();
		this.tXOFY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.fdir.galileo.Dft.XOFY");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.dlr.sc.virsat.fdir.galileo.Dft".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//GalileoDft:
	//	'toplevel' root=[GalileoFaultTreeNode|STRING] ';' (gates+=GalileoGate ';' | basicEvents+=GalileoBasicEvent ';')*;
	public GalileoDftElements getGalileoDftAccess() {
		return pGalileoDft;
	}
	
	public ParserRule getGalileoDftRule() {
		return getGalileoDftAccess().getRule();
	}
	
	//GalileoGate GalileoFaultTreeNode:
	//	name=STRING type=GalileoNodeType children+=[GalileoFaultTreeNode|STRING]*;
	public GalileoGateElements getGalileoGateAccess() {
		return pGalileoGate;
	}
	
	public ParserRule getGalileoGateRule() {
		return getGalileoGateAccess().getRule();
	}
	
	//GalileoBasicEvent GalileoFaultTreeNode:
	//	name=STRING 'lambda' '=' lambda=Float ('dorm' '=' dorm=Float)? ('repair' '=' repair=Float)?;
	public GalileoBasicEventElements getGalileoBasicEventAccess() {
		return pGalileoBasicEvent;
	}
	
	public ParserRule getGalileoBasicEventRule() {
		return getGalileoBasicEventAccess().getRule();
	}
	
	//GalileoNodeType:
	//	Named | Observer | RDEP | Delay;
	public GalileoNodeTypeElements getGalileoNodeTypeAccess() {
		return pGalileoNodeType;
	}
	
	public ParserRule getGalileoNodeTypeRule() {
		return getGalileoNodeTypeAccess().getRule();
	}
	
	//Named GalileoNodeType:
	//	{Named} typeName=('and' | 'or' | XOFY | 'pand' | 'pand_i' | 'por' | 'por_i' | 'sand' | 'hsp' | 'wsp' | 'csp' | 'seq'
	//	| 'fdep');
	public NamedElements getNamedAccess() {
		return pNamed;
	}
	
	public ParserRule getNamedRule() {
		return getNamedAccess().getRule();
	}
	
	//Observer GalileoNodeType:
	//	{Observer} 'observer' observables+=[GalileoFaultTreeNode|STRING]* 'obsRate' '=' observationRate=Float;
	public ObserverElements getObserverAccess() {
		return pObserver;
	}
	
	public ParserRule getObserverRule() {
		return getObserverAccess().getRule();
	}
	
	//RDEP GalileoNodeType:
	//	{Rdep} 'rdep' 'rateFactor' rateFactor=Float;
	public RDEPElements getRDEPAccess() {
		return pRDEP;
	}
	
	public ParserRule getRDEPRule() {
		return getRDEPAccess().getRule();
	}
	
	//Delay GalileoNodeType:
	//	{Delay} 'delay' 'time' time=Float;
	public DelayElements getDelayAccess() {
		return pDelay;
	}
	
	public ParserRule getDelayRule() {
		return getDelayAccess().getRule();
	}
	
	//Float:
	//	'-'? INT ('.' INT)? ('e' '-'? INT)?;
	public FloatElements getFloatAccess() {
		return pFloat;
	}
	
	public ParserRule getFloatRule() {
		return getFloatAccess().getRule();
	}
	
	//terminal XOFY:
	//	INT 'of' INT;
	public TerminalRule getXOFYRule() {
		return tXOFY;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
