/*
 * generated by Xtext 2.12.0
 */
package de.dlr.sc.virsat.fdir.galileo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DftAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/dlr/sc/virsat/fdir/galileo/parser/antlr/internal/InternalDft.tokens");
	}
}
