/**
 * generated by Xtext 2.18.0.M3
 */
package de.dlr.sc.virsat.fdir.galileo.dft.impl;

import de.dlr.sc.virsat.fdir.galileo.dft.DftPackage;
import de.dlr.sc.virsat.fdir.galileo.dft.GalileoFaultTreeNode;
import de.dlr.sc.virsat.fdir.galileo.dft.Observer;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Observer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.ObserverImpl#getObservables <em>Observables</em>}</li>
 *   <li>{@link de.dlr.sc.virsat.fdir.galileo.dft.impl.ObserverImpl#getObservationRate <em>Observation Rate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObserverImpl extends GalileoNodeTypeImpl implements Observer
{
  /**
   * The cached value of the '{@link #getObservables() <em>Observables</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObservables()
   * @generated
   * @ordered
   */
  protected EList<GalileoFaultTreeNode> observables;

  /**
   * The default value of the '{@link #getObservationRate() <em>Observation Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObservationRate()
   * @generated
   * @ordered
   */
  protected static final String OBSERVATION_RATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getObservationRate() <em>Observation Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObservationRate()
   * @generated
   * @ordered
   */
  protected String observationRate = OBSERVATION_RATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObserverImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DftPackage.Literals.OBSERVER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GalileoFaultTreeNode> getObservables()
  {
    if (observables == null)
    {
      observables = new EObjectResolvingEList<GalileoFaultTreeNode>(GalileoFaultTreeNode.class, this, DftPackage.OBSERVER__OBSERVABLES);
    }
    return observables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getObservationRate()
  {
    return observationRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObservationRate(String newObservationRate)
  {
    String oldObservationRate = observationRate;
    observationRate = newObservationRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DftPackage.OBSERVER__OBSERVATION_RATE, oldObservationRate, observationRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DftPackage.OBSERVER__OBSERVABLES:
        return getObservables();
      case DftPackage.OBSERVER__OBSERVATION_RATE:
        return getObservationRate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DftPackage.OBSERVER__OBSERVABLES:
        getObservables().clear();
        getObservables().addAll((Collection<? extends GalileoFaultTreeNode>)newValue);
        return;
      case DftPackage.OBSERVER__OBSERVATION_RATE:
        setObservationRate((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DftPackage.OBSERVER__OBSERVABLES:
        getObservables().clear();
        return;
      case DftPackage.OBSERVER__OBSERVATION_RATE:
        setObservationRate(OBSERVATION_RATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DftPackage.OBSERVER__OBSERVABLES:
        return observables != null && !observables.isEmpty();
      case DftPackage.OBSERVER__OBSERVATION_RATE:
        return OBSERVATION_RATE_EDEFAULT == null ? observationRate != null : !OBSERVATION_RATE_EDEFAULT.equals(observationRate);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (observationRate: ");
    result.append(observationRate);
    result.append(')');
    return result.toString();
  }

} //ObserverImpl
