/*
 * generated by Xtext 2.22.0
 */
package de.dlr.sc.virsat.fdir.galileo.ui;

import com.google.inject.Injector;
import de.dlr.sc.virsat.fdir.galileo.ui.internal.GalileoActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DftExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GalileoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GalileoActivator activator = GalileoActivator.getInstance();
		return activator != null ? activator.getInjector(GalileoActivator.DE_DLR_SC_VIRSAT_FDIR_GALILEO_DFT) : null;
	}

}
